### PR TITLE
Handle monitor scaling

### PR DESCRIPTION
**Pull request by aaronjamt**
Multiplies by monitor scale factor to support monitors with different scale factors

### CODE REVIEW

**Comment by thrombe** [comment]
is the grid rendering broken without this scale factor?
how do i reproduce and observe this broken behavior?

**Comment by aaronjamt** [comment]
> is the grid rendering broken without this scale factor?

Yes, see screenshot.

> how do i reproduce and observe this broken behavior?

Set your monitor to have a scale factor of something other than 1 in Hyprland config, i.e.:
`monitor=eDP-1,preferred,0x0,1.567`

**Comment by aaronjamt** [comment]
Here is also a video demonstrating the current behavior: https://photos.app.goo.gl/q4DqG3aosFAvPaRH6

**Comment by thrombe** [comment]
thanks for the PR!

**Comment by aaronjamt** [comment]
Thanks for merging it! Glad to help.

**Pull request merged**
